### ISSUE TITLE
Port cart. force / toque (wrench?) data type

### ISSUE THREAD

**Issue by swrede** [corlab/rst-rt#2]

**Comment by smithjoshua001** [comment]
Has there been any progress on implementing this data type? I would like to use it for transmitting force torque sensor data

**Comment by xwavex** [comment]
@smithjoshua001 I'll try to target that tomorrow, shouldn't take too much time.

**Comment by xwavex** [comment]
@smithjoshua001 The following Types are now included:

[rst.dynamics.Forces](http://docs.cor-lab.de//rst-manual/trunk/html/generated/stable/package-rst-dynamics.html?highlight=forces#rst.dynamics.Forces)

``` php
message Forces {

    /**
     * Translatory force along the x axis.
     */
    // @unit(newton)
    required float x = 1;

    /**
     * Translatory force along the y axis.
     */
    // @unit(newton)
    required float y = 2;

    /**
     * Translatory force along the z axis.
     */
    // @unit(newton)
    required float z = 3;

}
```

[rst.dynamics.Torques](http://docs.cor-lab.de//rst-manual/trunk/html/generated/stable/package-rst-dynamics.html?highlight=torques#rst.dynamics.Torques)

``` php
message Torques {

    /**
     * Torque around the x axis.
     */
    // @unit(newton-meter)
    required float a = 1;

    /**
     * Torque around the y axis.
     */
    // @unit(newton-meter)
    required float b = 2;

    /**
     * Torque around the z axis.
     */
    // @unit(newton-meter)
    required float c = 3;

}
```

[rst.dynamics.Wrench](http://docs.cor-lab.de//rst-manual/trunk/html/generated/stable/package-rst-dynamics.html?highlight=wrench#rst.dynamics.Wrench)

``` php
message Wrench {

    /**
     * 3-dimensional translatory forces.
     */
    required Forces forces = 1;

    /**
     * 3-dimensional rotatory forces (moment).
     */
    required Torques torques = 2;

}
```
