### ISSUE TITLE
"Forces" name missleading

### ISSUE THREAD

**Issue by ndehio** [corlab/rst-rt#8]
It seems, that the realtime-type "Forces" comprises a single, three-dimensional force only.
In comparison, the realtime-type "JointTorques" comprises a vector of torques.

This naming leads to misunderstanding. 
I suggest to either rename "Forces" to "Force" to make clear that this type comprises a single force (in three-dimensional space) or to reimplement this type such that it contains a vector of (three-dimensional) forces.

**Comment by ndehio** [comment]
Similar holds for the type "Torques" which represents a single three-dimensional torque instead of a vector of Torques.

**Comment by xwavex** [comment]
I agree that it could be misleading in some cases, but since we want to mirror the existing RST types, it is conform w.r.t. RST, e.g. http://docs.cor-lab.org/rst-manual/trunk/html/generated/stable/package-rst-dynamics.html?highlight=torques#rst.dynamics.Torques

**Comment by xwavex** [comment]
Given the aforementioned reason, I will close this issue.
It might be reopened if either RST-RT is not mirroring RST anymore or the particular types are changed in RST itself.
